### ISSUE TITLE
minor::mistype in INFO output

### ISSUE THREAD

**Issue by ksiv** [mojohaus/templating-maven-plugin#19]
[INFO] Coping files with filtering to temporary directory.
"Copying" misses "y"

**Comment by mbenson** [comment]
Still a problem. https://github.com/mojohaus/templating-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/templating/AbstractFilterSourcesMojo.java#L143

**Comment by slachiewicz** [comment]
Thx!
