### ISSUE TITLE
Mechanism to declare target package name for generated classes should be documented

### ISSUE THREAD

**Issue by rpastrana** [mojohaus/templating-maven-plugin#24]
Provide optional mechanism to declare target package for generated class(es)

**Comment by khmarbaise** [comment]
Maybe I misunderstand that but if you put the template file into `/src/main/java-templates` plus the needed package like `/src/main/java-templates/com/xy/whatever/Template.java` the package will be generated as wished?

**Comment by rpastrana** [comment]
Hi @khmarbaise please see my proposed solution: https://github.com/mojohaus/templating-maven-plugin/pull/25
It exposes an optional "packagename" parameter, if filled in, the generated class is copied to that package.

The problem we had, was that we couldn't import the generated class from other packages.
This happened even if we changed the outputDirectory because it's always added as a src root:


protected void addSourceFolderToProject( MavenProject mavenProject )
{
       mavenProject.addCompileSourceRoot( getOutputDirectory().getAbsolutePath() );
}

**Comment by khmarbaise** [comment]
What I don't understand is the part: `The problem we had, was that we couldn't import the generated class from other packages.` in the end it's a usual class so why couldn't you import a class from a package? 

Apart from that the outputDirectory should never been changed simply.

**Comment by rpastrana** [comment]
The resulting class is placed in an unnamed namespace, it's my understanding classes from the unnamed namespace are not in scope in an import declaration.

**Comment by khmarbaise** [comment]
The generated class is only placed into default package if you put the template class into that location which would mean `/src/main/java-templates/XYZ.java`. If you put the template class into the appropriate package location ( `/src/main/java-templates/com/xy/whatever/XYZ.java`) the class will be generated into the appropriate package. (as I wrote in my first comment).

**Comment by rpastrana** [comment]
got it, you posted it as a question. Was this discussed in the docs explicitly?

**Comment by kohlschuetter** [comment]
I think this ticket can be closed now.

From the [documentation](http://www.mojohaus.org/templating-maven-plugin/filter-sources-mojo.html):
"sourceDirectory — Source directory that will be first filtered and then added as a classical source folder."

I think this is (now?) sufficiently documented. "Classical" Java source folders are arranged in a way one would expect — packages are directory paths, and the Java files declared in a particular package are files below the path defined by the package name (`com.example.xyz.MyClass` -> com/example/xyz/MyClass.java).

This is also what IDEs like Eclipse expect, and adding the package name through a Maven property as proposed in https://github.com/mojohaus/templating-maven-plugin/pull/25 would break a lot of conventional assumptions.

If moving files is truly desired, consider using another plugin, such as [copy-rename-maven-plugin](https://github.com/kohlschutter/copy-rename-maven-plugin), for example.
