### ISSUE TITLE
Use of maven profiles

### ISSUE THREAD

**Issue by maqjav** [mojohaus/templating-maven-plugin#26]
Hello.

In my project we have the next configuration:

```xml
<properties>
    <myProperty>defaultValue</myProperty>
</properties>
<profiles>
    <profile>
        <id>pre</id>
        <properties>
             <myProperty>valuePre</myProperty>
        </properties>
    </profile>
    <profile>
         <id>pro</id>
         <properties>
              <myProperty>valuePro</myProperty>
        </properties>
    </profile>
</profiles>
```

We use the default configuration of the plugin, and the goal "filter-sources".

We have a file where we are replacing the property ${myProperty} and the pluging works as intended, generating the java file with the value "defaultValue". However, if I try to compile the project with another profile, it is ignored, and the default value is taken.

Example:

`mvn clean install -Ppre`

The result is a .class file with the value "defaultValue".

Is there something I'm doing wrong or the plugin is not taking into account profiles?

Thanks.

**Comment by kohlschuetter** [comment]
I've tried to reproduce this issue with the latest code and Maven 3.9.3, but it all works as expected.
I think this issue can be closed now.

**Comment by maqjav** [comment]
I will update to the latest version next week when I'm back at work and I will let you know.
Thanks for the information.

**Comment by kohlschuetter** [comment]
@maqjav Please make sure to use the latest source (I've tested b94303a), not the released version.
