### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by norrisjeremy** [mojohaus/templating-maven-plugin#54]
Is this project abandoned, or are there plans to update and release new versions?
The latest 3.9.2 Maven release generates the following warnings with the last published version (1.0.0, from 2015):
```
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

**Comment by norrisjeremy** [comment]
Also, testing the current `3.0.0-SNAPSHOT` build locally produces the following warnings from Maven 3.9.2:
```
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.2.5, org.apache.maven:maven-model:3.2.5, org.apache.maven:maven-core:3.2.5, org.apache.maven:maven-settings:3.2.5, org.apache.maven:maven-model-builder:3.2.5, org.apache.maven:maven-repository-metadata:3.2.5, org.apache.maven:maven-aether-provider:3.2.5, org.apache.maven:maven-settings-builder:3.2.5, org.apache.maven:maven-artifact:3.2.5]
```

**Comment by kohlschuetter** [comment]
It looks like most issues have been addressed on May 12 (a day after this issue has been filed), so I assume there's a new release around the corner, @slachiewicz ?

**Comment by slachiewicz** [comment]
I've created release 3.0.0, which will soon be available on Maven Central
https://repo.maven.apache.org/maven2/org/codehaus/mojo/templating-maven-plugin/
