### ISSUE TITLE
Make a release 1.0.0 into Maven central

### ISSUE THREAD

**Issue by cardil** [mojohaus/templating-maven-plugin#6]
Make a release to official Maven central repository with actual code, version `1.0.0`.

As a bonus a shield with Maven repo would be nice in README.md, like this (dynamic one):

[![Maven Central](https://img.shields.io/maven-central/v/org.codehaus.mojo/templating-maven-plugin.svg)](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.codehaus.mojo%22%20AND%20a%3A%22templating-maven-plugin%22)

BTW. About shield, goto: http://shields.io/

**Comment by cardil** [comment]
@pfoermer in https://github.com/wavesoftware/templating-maven-plugin-copy/issues/1#issuecomment-157673795

**Comment by cardil** [comment]
There is a GIT release 4 days ago but jar is not present in Maven central? Is there some kind of hold up?

**Comment by khmarbaise** [comment]
The VOTE took a little bit...i have released the artifact from nexus repository...this will take a little to sync to central...Thanks for question...

**Comment by cardil** [comment]
Nice. I will finally could use official versions in my company :-)

**Comment by pfoermer** [comment]
Great! A big "thank you" to all who participated into this official release.
